/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (54.48%)
 * Likes:    687
 * Dislikes: 268
 * Total Accepted:    182K
 * Total Submissions: 333.9K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */

// @lc code=start
class Solution {
 public:
  char findTheDifference(string s, string t) {
    array<int, 26> charCnt{0};

    for (const auto& c : s) {
      ++charCnt[c - 'a'];
    }

    for (const auto& c : t) {
      if (charCnt[c - 'a'] == 0) {
        return c;
      } else {
        --charCnt[c - 'a'];
      }
    }

    return ' ';
  }
};
// @lc code=end
